<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="7" hostname="SEZT1FF266MANGO" name="com.employeeapi.testcases.TC005_Delete_Employee_Record" tests="8" failures="0" timestamp="24 Sep 2020 12:41:28 GMT" time="1.199" errors="1">
  <testcase name="checkStatusCode" time="0.000" classname="com.employeeapi.testcases.TC005_Delete_Employee_Record">
    <skipped/>
  </testcase> <!-- checkStatusCode -->
  <testcase name="deleteEmployees" time="1.199" classname="com.employeeapi.testcases.TC005_Delete_Employee_Record">
    <error type="io.restassured.path.json.exception.JsonPathException" message="Failed to parse the JSON document">
      <![CDATA[io.restassured.path.json.exception.JsonPathException: Failed to parse the JSON document
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1002)
at io.restassured.path.json.JsonPath$4.doParseWith(JsonPath.java:967)
at io.restassured.path.json.JsonPath$JsonParser.parseWith(JsonPath.java:1047)
at io.restassured.path.json.JsonPath.get(JsonPath.java:202)
at com.employeeapi.testcases.TC005_Delete_Employee_Record.deleteEmployees(TC005_Delete_Employee_Record.java:29)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:168)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: groovy.json.JsonException: Lexing failed on line: 1, column: 1, while reading '<', no possible valid JSON value or punctuation could be recognized.
at groovy.json.JsonLexer.nextToken(JsonLexer.java:86)
at groovy.json.JsonLexer$nextToken.call(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:130)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parse(ConfigurableJsonSlurper.groovy:97)
at io.restassured.internal.path.json.ConfigurableJsonSlurper$parse.callCurrent(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:171)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
at io.restassured.internal.path.json.ConfigurableJsonSlurper.parseText(ConfigurableJsonSlurper.groovy:83)
at io.restassured.path.json.JsonPath$4$1.method(JsonPath.java:965)
at io.restassured.path.json.JsonPath$ExceptionCatcher.invoke(JsonPath.java:1000)
... 30 more
]]>
    </error>
  </testcase> <!-- deleteEmployees -->
  <testcase name="checkStatusLine" time="0.000" classname="com.employeeapi.testcases.TC005_Delete_Employee_Record">
    <skipped/>
  </testcase> <!-- checkStatusLine -->
  <testcase name="checkContentLength" time="0.000" classname="com.employeeapi.testcases.TC005_Delete_Employee_Record">
    <skipped/>
  </testcase> <!-- checkContentLength -->
  <testcase name="checkResponseTime" time="0.000" classname="com.employeeapi.testcases.TC005_Delete_Employee_Record">
    <skipped/>
  </testcase> <!-- checkResponseTime -->
  <testcase name="checkServerType" time="0.000" classname="com.employeeapi.testcases.TC005_Delete_Employee_Record">
    <skipped/>
  </testcase> <!-- checkServerType -->
  <testcase name="checkContentType" time="0.000" classname="com.employeeapi.testcases.TC005_Delete_Employee_Record">
    <skipped/>
  </testcase> <!-- checkContentType -->
  <testcase name="checkResponseBody" time="0.000" classname="com.employeeapi.testcases.TC005_Delete_Employee_Record">
    <skipped/>
  </testcase> <!-- checkResponseBody -->
</testsuite> <!-- com.employeeapi.testcases.TC005_Delete_Employee_Record -->
